all: test debug_large debug_test debug_test2 debug_test3

test:
	g++ -o Buffer-test Buffer-test.cc Buffer.cc

debug_large:
	g++ -o debug_large Buffer.cc debug_large.cc

debug_test:
	g++ -o debug_test Buffer.cc debug_test.cc

debug_test2:
	g++ -o debug_test2 Buffer.cc debug_test2.cc

debug_test3:
	g++ -o debug_test3 Buffer.cc debug_test3.cc